name: PR check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  install:
    name: install packages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: install
        run: |
          pip install poetry
          poetry install

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Test
        run: pytest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Lint
        run: ruff check
