name: PR check

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
      
      - name: Verify Poetry installation
        run: |
          poetry --version
          echo $PATH
      
      - name: poetry install
        run: poetry install

      - name: Lint
        run: poetry run ruff check

      - name: Test
        run: poetry run pytest
